title: S&C Knowledge Base
description: S&C Associates' Knowledge Base Articles
theme: just-the-docs

url: https://sandcassociates.github.io/knowledge-base/

aux_links:
  S&C's GitHub Repo: https://github.com/sandcassociates/knowledge-base

callouts:
    note:
        title: note
        color: blue
    alert:
        title: alert
        color: yellow
    important:
        title: important
        color: red
mermaid:
  version: "9.1.6"

color_scheme: blue

favicon_ico: "/assets/images/S_C_logo.png"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 S&C Associates"
