title: S&C Knowledge Base
description: S&C Associates' Knowledge Base Articles
theme: just-the-docs

url: https://sandcassociates.github.io/knowledge-base/

aux_links:
  S&C's GitHub Repo: https://github.com/sandcassociates/knowledge-base

callouts:
    note:
        title: note
        color: blue
    alert:
        title: alert
        color: yellow
    important:
        title: important
        color: red
mermaid:
  version: "9.1.6"